apiVersion: v1
kind: Service
metadata:
  name: devops-showcase
  namespace: devops-showcase
spec:
  type: LoadBalancer
  selector:
    app: devops-showcase
  ports:
    - port: 80
      targetPort: 80
